name: mlflow-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.13
  - pyyaml
  - pip=24.3.1
  - pip:
      - mlflow==3.4.0
      - wandb==0.22.0
      - hydra-core==1.3.3
      - pandas==2.3.2
      - matplotlib==3.10.6

