name: test_regression_model
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.13
  - numpy>=1.26
  - scipy=1.14
  - pandas=2.3.2
  - pip=24.3.1
  - scikit-learn=1.7.2
  - pip:
      - mlflow==3.4.0
      - wandb==0.22.0
      - git+https://github.com/udacity/Project-Build-an-ML-Pipeline-Starter.git#egg=wandb-utils&subdirectory=components
